# Generated by Django 3.0.7 on 2020-06-24 11:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200624_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_count', wagtail.core.blocks.StructBlock([('title_and_count', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('icon', wagtail.core.blocks.CharBlock(defualt='xxx', help_text='Add class icon of title', required=True)), ('count', wagtail.core.blocks.TextBlock(help_text='Add count', required=True))])))]))], blank=True, null=True),
        ),
    ]
