# Generated by Django 3.0.7 on 2020-06-25 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0008_auto_20200624_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_cta_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle_head_page',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_head_page',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
