# Generated by Django 3.0.7 on 2020-06-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200625_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_cta_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle_head_page',
        ),
        migrations.AddField(
            model_name='homepage',
            name='name_page',
            field=models.CharField(help_text='Add your page name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='url_page',
            field=models.URLField(help_text='Add your page URL', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_head_page',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
