# Generated by Django 3.0.7 on 2020-06-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200625_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='url_page',
        ),
        migrations.AddField(
            model_name='homepage',
            name='URL_page',
            field=models.URLField(help_text='Add your URL page ', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='name_page',
            field=models.CharField(help_text='Add your name page ', max_length=100, null=True),
        ),
    ]
